import{ADD_CARD,DELETE_CARD,EDIT_CARD} from '../action/ActionType'
const movieList=[
{ id:0,movieName:"Inception" ,movieDate:"2010", img:"https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg", ratingMovie: 5,movieDescription:"Inception is a 2010 science fiction action film[3] written and directed by Christopher Nolan, who also produced the film with his wife, Emma Thomas. The film stars Leonardo DiCaprio as a professional thief who steals information by infiltrating the subconscious of his targets. He is offered a chance to have his criminal history erased as payment for the implantation of another person's idea into a target's subconscious.[4] The ensemble cast includes Ken Watanabe, Joseph Gordon-Levitt, Marion Cotillard, Ellen Page, Tom Hardy, Dileep Rao, Cillian Murphy, Tom Berenger, and Michael Caine."},

{ id:1, movieName:"Avatar" ,movieDate:"2009", img: "https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_.jpg", ratingMovie: 4,movieDescription:"Avatar (marketed as James Cameron's Avatar) is a 2009 American[8][9] epic science fiction film directed, written, produced, and co-edited by James Cameron and stars Sam Worthington, Zoe Saldana, Stephen Lang, Michelle Rodriguez, and Sigourney Weaver. The film is set in the mid-22nd century when humans are colonizing Pandora, a lush habitable moon of a gas giant in the Alpha Centauri star system, in order to mine the mineral unobtanium,[10][11] a room-temperature superconductor.[12] The expansion of the mining colony threatens the continued existence of a local tribe of Na'vi – a humanoid species indigenous to Pandora. The film's title refers to a genetically engineered Na'vi body operated from the brain of a remotely located human that is used to interact with the natives of Pandora." },

{ id:2, movieName: "Joker", movieDate:"2019",img: "https://img.yts.lt/assets/images/movies/joker_2019/medium-cover.jpg",ratingMovie: 4,movieDescription:"Joker is a 2019 American psychological thriller film directed and produced by Todd Phillips, who co-wrote the screenplay with Scott Silver. The film, based on DC Comics characters, stars Joaquin Phoenix as the Joker. Joker provides a possible origin story for the character; set in 1981, it follows Arthur Fleck, a failed stand-up comedian whose descent into insanity and nihilism inspires a violent counter-cultural revolution against the wealthy in a decaying Gotham City. Robert De Niro, Zazie Beetz, Frances Conroy, Brett Cullen, Glenn Fleshler, Bill Camp, Shea Whigham, and Marc Maron appear in supporting roles. Joker was produced by Warner Bros. Pictures, DC Films, and Joint Effort, in association with Bron Creative and Village Roadshow Pictures, and distributed by Warner Bros."},

{ id:3,movieName: "Mission Impossible", movieDate:"2018",
 img:"https://img.yts.lt/assets/images/movies/mission_impossible_fallout_2018/medium-cover.jpg" ,ratingMovie: 2,movieDescription:"Mission: Impossible – Fallout is a 2018 American action spy film written, co-produced, and directed by Christopher McQuarrie. It is the sixth installment in the Mission: Impossible film series, and the second film to be directed by McQuarrie following the 2015 film Rogue Nation, making him the first director to direct more than one film in the franchise. The cast includes Tom Cruise, Ving Rhames, Simon Pegg, Rebecca Ferguson, Sean Harris, Michelle Monaghan, and Alec Baldwin, all of whom reprise their roles from previous films, along with Henry Cavill, Vanessa Kirby, and Angela Bassett, who join the franchise. In the film, Ethan Hunt and his team must track down missing plutonium while being monitored by a CIA agent after a mission goes wrong."},

 {  id:4,movieName:"Twilight ",movieDate:"2008",img:"https://static.accessonline.com/uploads/83447.jpg",ratingMovie:4,movieDescription:"Twilight is a 2008 American romantic fantasy film based on Stephenie Meyer's 2005 novel of the same name. Directed by Catherine Hardwicke, the film stars Kristen Stewart and Robert Pattinson. It is the first film in The Twilight Saga film series. This film focuses on the development of the relationship between Bella Swan (a teenage girl) and Edward Cullen (a vampire), and the subsequent efforts of Edward and his family to keep Bella safe from a coven of evil vampires.The project was in development for approximately three years at Paramount Pictures, during which time a screen adaptation that differed significantly from the novel was written. Summit Entertainment acquired the rights to the novel after three years of the project's stagnant development."},

{ id:5,movieName:"Forzen II ",movieDate:"2019",img:"https://moosegazette.net/wp-content/uploads/2019/11/114631/disneys-frozen-2-elsa-to-date-honeymaren-in-frozen-3.jpg",ratingMovie:4,movieDescription:"Frozen II, also known as Frozen 2, is a 2019 American 3D computer-animated musical fantasy film produced by Walt Disney Animation Studios. The 58th animated film produced by the studio, it is the sequel to the 2013 film Frozen and features the return of directors Chris Buck and Jennifer Lee, producer Peter Del Vecho, songwriters Kristen Anderson-Lopez and Robert Lopez, and composer Christophe Beck. Lee also returns as screenwriter, penning the screenplay from a story by her, Buck, Marc E. Smith, Anderson-Lopez, and Lopez,[2] while Byron Howard executive-produced the film.[a][1] Veteran voice cast Kristen Bell, Idina Menzel, Josh Gad, Jonathan Groff, and Ciarán Hinds return as their previous characters, and they are joined by newcomers Sterling K. Brown, Evan Rachel Wood, Alfred Molina, Martha Plimpton, Jason Ritter, Rachel Matthews, and Jeremy Sisto"},

{ id:6,movieName:"Masha ",movieDate:"2017",img:"http://nantes.aujourdhui.fr/uploads/assets/evenements/recto_fiche/2018/02/1160802_masha-et-michka-theatre-de-la-fleuriaye-carquefou-carquefou.jpg",ratingMovie:4,movieDescription:"Masha and the Bear (Russian: Ма́ша и Медве́дь, romanized: Masha i Medved; Russian pronunciation: [ˈmaʂə i mʲɪdˈvetʲ]) is a Russian animated television series created by Oleg Kuzovkov and produced by Animaccord Animation Studio (Moscow, the Russian Federation), loosely based on the oral children's folk story of the same name. The show focuses on the adventures of a little girl named Masha and a fatherly bear that always keeps her from disasters. The first episode was released in 2009.[1] It quickly became a phenomenon, and is the most-successful 21st-century animated series of Russian origin (Nu, pogodi! is more successful, but originated in 20th century, with most successful episodes being produced in that time, and when Soviet Union existed), and turned Animaccord, then a small studio, into a major domestic player in animated film industry."},

{ id:7,movieName:"Peppa Pig ",movieDate:"2003",img:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRV5NE_t2RoCuSD4YD6B30_xDsnTrccbGlotaaRN9ZT4o26PWKO",ratingMovie:3,movieDescription:"Peppa Pig is a British preschool animated television series directed and produced by Astley Baker Davies in association with Entertainment One, Nick Jr., Channel 5 and Hasbro's Allspark Animation. The show revolves around Peppa, an anthropomorphic female pig, and her family and peers. The show originally aired on 31 May 2004, and there have been six series as of 2019, the most recent of which commenced broadcasting in February 2019 in the UK. The series is shown in 180 territories including the UK and US.[1] Reruns were also aired on the Nick Jr. on Nick block starting on 25 December 2017. However, the reruns were removed on 9 February 2019"},

{ id:8,movieName:"Ladybug",movieDate:"2015",img:"https://images-na.ssl-images-amazon.com/images/I/71PjEIQjnYL._AC_SY606_.jpg",ratingMovie:5,movieDescription:"Miraculous: Tales of Ladybug & Cat Noir (French: Miraculous, les aventures de Ladybug et Chat Noir; also known as Miraculous Ladybug or Miraculous) is a computer animated superhero animated series produced by French studios Zagtoon and Method Animation in collaboration with De Agostini Editore S.p.A. in Italy, Toei Animation in Japan, SAMG Animation in South Korea, DQ Entertainment and Assemblage Entertainment in India, and Globosat in Brazil.[2][21][7][8] The series features two Parisian teenagers, Marinette Dupain-Cheng and Adrien Agreste, who transform into the superheroes Ladybug and Cat Noir, respectively, to protect the city from supervillains."},

{ id:9,movieName:"Sofia",movieDate:"2018",img:"https://media.senscritique.com/media/000006560973/source_big/Princesse_Sofia.jpg",ratingMovie:4,movieDescription:"Sofia the First is an American animated television series that premiered on November 18, 2012, produced by Disney Television Animation for Disney Channel and Disney Junior. Jamie Mitchell is the director and executive producer and Craig Gerber serves as creator, story editor and producer. The show follows the adventures of Sofia, played by Ariel Winter. Sofia becomes a princess when her mother, Miranda, marries King Roland II of Enchancia. The show features songs by John Kavanaugh and Erica Rothschild and a musical score by Kevin Kliesch.[4] The show had its final episode on September 8, 2018."}
]

export const reducerMovie=(state=movieList,action)=>{
    switch(action.type){
        case ADD_CARD:
            return(state.concat(action.payload));
       
        case DELETE_CARD:
            return(state.filter(el=>el.id!==action.payload)
            );
          
        case EDIT_CARD:
            return state.map(el =>el.id === action.payload.id ? ({ ...el } = { ...action.payload }) : el);
            default:
                return state;  
    }

}